name: CPU Load Alert Release

on:
  push:
    branches:
      - main  # Only triggers when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this secret is set in your repository
        with:
          tag_name: ${{ github.sha }}  # Uses commit SHA as the tag
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
          body: |
            ## Changelog
            - Describe changes in this release
            - Another change here
