name: Release

on:
  push:
    tags:
      -  'v*' # This triggers on tags like v1.0.0, v2.0.0 like wise
    branches:
      - main # Only triggers when tags are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            This is an automated release.
            fror details, checkout the [README](https://github.com/thurunu/cpu-load-alert#readme).
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass the GitHub token
