name: CPU Load Alert Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow only when a new tag with 'v*' (e.g., v1.0.0) is pushed.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure you have this secret configured in GitHub settings
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## Changelog
            - Describe changes in this release
            - Another change here
